schemaLocation: "./schemas/fpml-5-13/confirmation/fpml-main-5-13.xsd"

target:
  namespace: "fpml.confirmation"
  namespaceDefinition: "fpml.confirmation definition"
  nameOverrides:
    "Prepayment": "LoanPrepayment"  # complex type
    "prepayment": "LoanPrepayment"  # element
  preferences:
    enumValueCasing: KeepOriginal
