schemaLocation: "./schemas/fpml-5-13/confirmation/fpml-main-5-13.xsd"

target:
  namespace: "fpml.confirmation"
  namespaceDefinition: "fpml.confirmation definition"
  nameOverrides:
    "a": "b"  # cannot be empty... TODO
