schemaLocation: "./schemas/fpml-5-10/confirmation/fpml-main-5-10.xsd"

target:
  namespace: "fpml.confirmation"
  namespaceDefinition: "fpml.confirmation definition"
  nameOverrides:
    "Prepayment": "LoanPrepayment"  # complex type
    "prepayment": "LoanPrepayment"  # element
  preferences:
    enumValueCasing: KeepOriginal
    xsdDateHandlingStrategy: "AS_RUNE_ZONED_DATE_TIME"