model:
  name: FpML
namespaceConfig:
- id: fpml513Confirmation
  namespace: fpml.consolidated
  readOnly: true
  schemaConfig:
    schema: fpml513Confirmation
    configPath: xml-config/fpml-5-13-confirmation-xml-config.json
- id: fpml513Recordkeeping
  namespace: fpml.consolidated
  readOnly: true
  schemaConfig:
    schema: fpml513Recordkeeping
    configPath: xml-config/fpml-5-13-recordkeeping-xml-config.json
